### ISSUE TITLE
Markers take a long time to render in latest version of Vidi

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#11]
When using latest version of Vidi its takes very long time before the application gets responsive again.
Checking out https://github.com/mapcentia/vidi/tree/2018.1 will fix the issue. So I guess its related to some changes in Vidi core and not the extension.

**Comment by sashuk** [comment]
For reference: the problem appeared at https://github.com/sashuk/vidi/commit/35cbf28000ab19dce19722dd32853d2adb56e51d

**Comment by sashuk** [comment]
The reason why `watsonc` started taking too much time to load is that after https://github.com/sashuk/vidi/commit/35cbf28000ab19dce19722dd32853d2adb56e51d it actually started working right: before merge when `loadDataInTable()` was executed every time, the `$(el).bootstrapTable("load", data);` was silently crashing as it could not find the node. After the merge nodes for table view appeared, so Bootstrap tables were created every time and when there was too much data (like in `watsonc` case) the table initialization process was freezing the entire applcation.

What was done: creating and updating the Bootstrap table only when it is visible. In case of `watsonc` it is actually never drawn because of `layerTree` panel settings.

Implemented in https://github.com/sashuk/vidi/commit/ecfd481d3ed58a929874e3e89b272300174c3d87 and https://github.com/sashuk/vidi/commit/a96a8564289c387984480b593afafead77b1c95d
