### ISSUE TITLE
Correction of data in sensor.sensordata_without_correction

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#4]
The data in `sensor.sensordata_without_correction` comes from sensors placed outside on fields. Sometimes cows trip over them and alter the height the sensors have over ground level. When a displacement occurs, the time is logged in this table:
https://watsonc-map.gc2.io/api/sql/jupiter?q=SELECT%20*%20FROM%20sensor.sensorlevcorr
The idea is to adjust the following measurements after a displacement. So its assumed that the first measurement just after a displacement is the same as the one just before. And all following measurements should be adjusted with the same value until next displacement occurs.

Example of a displacement:
![image](https://user-images.githubusercontent.com/3850918/49371915-4766a900-f6f9-11e8-8161-75e7472c7c39.png)

**Comment by sashuk** [comment]
@mapcentia So, there is some numeric difference between neighbour measurements that is considered to be a **displacement**? And using this numeric value, corrections are proposed to be performed on the client-side?

**Comment by mapcentia** [comment]
@sashuk No, the displacement is manual detected and logged in the table:
https://watsonc-map.gc2.io/api/sql/jupiter?q=SELECT%20*%20FROM%20sensor.sensorlevcorr
When the WatsonC people see a jump in the plot, they input the date/time in the above mentioned table.
The corrections are proposed to be performed on the client-side.

**Comment by sashuk** [comment]
@mapcentia Thanks, got it! Yes, it will be implemented

**Comment by sashuk** [comment]
@mapcentia Could you please specify if the `stationid` in correction data table actually corresponds to the `gid` field of corrected station in table with water level measurements?

Also corrections have date in `2018-09-17 19:31:52+02` format, whenever measurement dates are in `2018-07-25T09:30:58` format. Is it correct to transform correction date to UTC or just ignore the +2 time zone?

**Comment by mapcentia** [comment]
@sashuk `boreholeno` is `stationid`. I used this alias in the database view, because I believe there has to be a field called `boreholeno`?

**Comment by sashuk** [comment]
@mapcentia There is such field indeed, thanks!

**Comment by sashuk** [comment]
@mapcentia Correction has `boreholeno` and `date`. If there are more than one intake for the borehole, do we assume the displacement was occured for both intakes?

Also corrections have date in 2018-09-17 19:31:52+02 format, whenever measurement dates are in 2018-07-25T09:30:58 format. Is it correct to transform correction date to UTC or just ignore the +2 time zone? Right now the correction is parsed, but adjoining measurements do not have spread in values.

**Comment by mapcentia** [comment]
@sashuk Yes, displacement is for both intakes (intakes in this case are sensors attached to samme station)
I'm not sure if measurement dates are in UTC or CET. But I'm guessing they are in UTC, so let us ransform correction dates to UTC.

**Comment by sashuk** [comment]
@mapcentia Thanks! Is it okay if some measurements have the exact same time of measurement?

![time](https://user-images.githubusercontent.com/1390758/49448509-044d2880-f814-11e8-9899-f2748dfe3166.png)

Also is the correction `date` always **between** measurements that have displacement between them?

**Comment by mapcentia** [comment]
@sashuk I'll check the same time isssue. Maybe is OK or it can be in the database VIEWs.
I don't think we can be sure correction is always between. It may be equal, because its manual logged. But its makes no sense to have an  correction equal to a measurement.

**Comment by sashuk** [comment]
@mapcentia Example: the **35** borehole has 2 corrections available: `2018-08-28 16:18:12+02` and `2018-08-04 21:49:18+02`. The shown demos without and with correction show that two smaller displacements are removed from graph, the biggest one was left, though, as it does not have an assigned correction.

Without correction:

![nocorrection](https://user-images.githubusercontent.com/1390758/49454071-62cbd400-f81f-11e8-9dcc-a15e041d0a32.gif)


With correction:

![withcorrection](https://user-images.githubusercontent.com/1390758/49454063-60697a00-f81f-11e8-9f86-c42dfe76b660.gif)

**Comment by sashuk** [comment]
Sorry, I meant `.. always between times of measurement that correspond to measurements that have displacement between them..`

> Also is the correction date always between measurements that have displacement between them?

**Comment by sashuk** [comment]
@mapcentia There are some cases when correction date is between measurement dates. For example, **borehole 34** has a correction with date `2018-08-01 08:20:50+02:00`, but if we look into data for this borehole, there are only times of measurement `2018-08-01T08:20:50` (with value **1320**) and `2018-08-01T09:20:53` (with value **1320000** - huge spike!).

So, in order to catch this case, the check if correction date is between two neighbour measurement dates has to be performed. During this check two `Date()` objects are created around 50 thousand times and comparison is carried out, which hangs browser for a long time (taking around 20 minutes for 2 x 2.5GHz Xeon 8GB RAM machine).

If this check is not performed (only the strict date comparison is performed), then the speed is acceptable but some correction cases are missed, please see the image below (left one is without corrections and the right one is with strict correction without range check - the biggest spike is actualy the example described above):

![2](https://user-images.githubusercontent.com/1390758/49459805-db845d80-f82a-11e8-93f9-19bcda1f7d68.png)

I would suggest to implement script that tries to set the closest measurement time for every made correction or to force users who enter corrections to set the closest existing measurement date (assuming that there can not be any new measurements between existing ones).

The code was implemented in https://github.com/sashuk/watsonc/commit/6d8c6c65b7bcb968ce91678efd83aa0678befedb

**Comment by mapcentia** [comment]
@sashuk 
The first is the logged correction time? And the second the measure time?
`2018-08-01  08:20:50+02:00`
`2018-08-01T08:20:50`
It looks like the logged correction is entered wrongly regarding time zone?

**Comment by sashuk** [comment]
@mapcentia Yes, however, I think that the time is correct in both cases, as the spike is between 8:20 and 9:20 and the correction is between 8:20 and 9:20 as well (if it was the time zone problem, than the difference will be a whole hour, in this case in it half an hour from 8:20 and half an hour to 9:20).

**Comment by mapcentia** [comment]
@sashuk 1320 ~ 1320,000 I tkink this is not a displacement but a change in units. I'll ask WatsonC about it

**Comment by mapcentia** [comment]
@sashuk regarding https://github.com/sashuk/watsonc/issues/4#issuecomment-444118753
Can you check that data point again? I replaced the view which about halved the points in the time series.

**Comment by sashuk** [comment]
@mapcentia No repeats, thanks!

![time](https://user-images.githubusercontent.com/1390758/49489318-5d08d980-f885-11e8-935d-ea3a5d235179.png)

**Comment by sashuk** [comment]
@mapcentia The very first correction for the **34 borehole** has following comment "Date must be the first point after the disturbance has occurred. The disturbance is expected to be due to cows" - maybe this correction is invalid from the very beginning, so such comment was left? Other corrections have comment "cows" and are working fine without range checks, so probably range checks are not even needed and task is actually already solved.

For now the range check was removed (https://github.com/sashuk/watsonc/commit/d6b70e1a749f7c43ca4777e97d3fabc169ce1944), corrections are applied according to these rules:
1. Correction date is the date of the first measurement where displacement occured;
2. Measurement times are given on `+0` timezone;
3. Correction times are given in `+2` timezone and are converted in `+0` timezone for quick string comparison with measurement times.

**Comment by mapcentia** [comment]
@sashuk It seems reasonable, that the first logged entry for **34** is left for sake of the comment. The actual comment is also quite clear about how adjustments dates should be logged

**Comment by sashuk** [comment]
@mapcentia Al right! Assuming that correction is performed according to rules above, the issue is implemented in https://github.com/sashuk/watsonc/commit/6d8c6c65b7bcb968ce91678efd83aa0678befedb
