### ISSUE TITLE
Profile tool

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#50]
**Changes**
leave "Opret nyt profil" and "Vælg tidligere oprettet profil" open when clicking "profiler"
![image](https://user-images.githubusercontent.com/50234893/59938269-ce406080-9454-11e9-8656-55ca7ed2df5f.png)

Set default buffer to 100 m

Change "tegne profil" to "Tegn profil"

![image](https://user-images.githubusercontent.com/50234893/59938531-8a019000-9455-11e9-863e-187acf04a43d.png)

After assigning profile title there should be a "Fortsæt" bottom instead of "save" icon that generated the profile

A new added profile should always be added to dashboard and map

![image](https://user-images.githubusercontent.com/50234893/59938776-3fccde80-9456-11e9-8dda-17d3d08010f0.png)

The check box activates display on dashboard (as now) and display line & buffer on the map 

The radio bottom may be deleted

The line on the map is labeled with "profile name"

**BUG**

The colors of the layers are random and not following the giver color scheme in the python script  

**Extensions**  

The next version of the profile script contains "chemical" data displayed on the profile and we will need a datatype (like compund no for "nitrat") as input to our python script (a new argument to the json object).

When the profile is generated you may use the selected datatype as input.
The selected datatype is displayed here
![image](https://user-images.githubusercontent.com/50234893/59940274-90463b00-945a-11e9-962f-3ee278903739.png)

and in the profile

![Dashboard ændring](https://user-images.githubusercontent.com/50234893/59940345-bec41600-945a-11e9-9c9d-dc42dc3d0d10.png)

the selected datatype may be changed by clicking 
![image](https://user-images.githubusercontent.com/50234893/59940441-fcc13a00-945a-11e9-927f-611e0057f759.png)

A different data type is selected from 
![image](https://user-images.githubusercontent.com/50234893/59940501-24180700-945b-11e9-899d-b4e1343c0978.png)

The profile i re-drawn with the new datatype.

**Comment by sashuk** [comment]
Overall progress:
- leave Profiler panels open when clicking "profiler"; :white_check_mark: 
- set default buffer to 100 m; :white_check_mark: 
- change "tegne profil" to "Tegn profil"; :white_check_mark: 
- the checkbox activates the display on the dashboard (as now) and display line & buffer on the map;  :white_check_mark: 
- the radio bottom may be deleted; :white_check_mark: 
- the line on the map is labeled with "profile name"; :white_check_mark: 
- the next version of the profile script contains "chemical" data displayed on the profile and we will need a datatype (like compound no for "nitrat") as input to our python script (a new argument to the json object); :white_check_mark: 
- when the profile is generated you may use the selected datatype as input. After assigning profile title there should be a "Fortsæt" bottom instead of "save" icon that generated the profile. A newly added profile should always be added to the dashboard and map; :white_check_mark: 
- the colors of the layers are random and not following the given color scheme in the python script; :white_check_mark: 
- the selected datatype may be changed by clicking; 
- the different data type is selected from data type selector control;

**Comment by sashuk** [comment]
@JacobBirk Could you please specify if all existing categories should be shown in the selector when entering a datatype for the created plot, or only those that correspond to currently enabled layers?

Also could you please specify where the latest Python script can be found?

**Comment by sashuk** [comment]
@JacobBirk I've received the invitation, thank you! Should I put the `intersectiontool.py` script in the provided repo as well or it can reside in the current repo (the only thing that it needs for work is the set of shapefiles which are checked for intersection, please see the https://github.com/sashuk/watsonc/tree/c3fc97a07d85cee1bbbc7b303a5e559ed751edb7/scripts - the `profil` folder does not exist, as it is the private repo and should be checked out separately)?

**Comment by JacobBirk** [comment]
@sashuk All existing categories:-)

Ok to leave the intersectiontool.py there is is

**Comment by sashuk** [comment]
@JacobBirk Thank you for the information! For now, everything is implemented except changing the data type for profiles in the Dashboard:

![profile1](https://user-images.githubusercontent.com/1390758/60514113-58b57980-9d0b-11e9-8307-37ff55d40c52.gif)

![profile2](https://user-images.githubusercontent.com/1390758/60514115-58b57980-9d0b-11e9-8e37-325cd13c59ef.gif)

Could you please specify if the new profile **should be created** when the new data type is selected for the profile or the existing profile should be **regenerated** with the new data type?

**Comment by JacobBirk** [comment]
Good question :-)
I think you should create a new one

**Comment by sashuk** [comment]
@JacobBirk Thanks you for the information!

@mapcentia @JacobBirk The creation of the profile that differs only in data type and title from the original one was implemented in https://github.com/sashuk/watsonc/commit/001d38edaeab6594141672dd55143ba01814247c

Demo:
![changingthedatatype](https://user-images.githubusercontent.com/1390758/60664890-9514e100-9e95-11e9-8d59-eac6fe56aed9.gif)
