### ISSUE TITLE
Bug - initial load of symbols

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#54]
Symbols are not loaded initially 
![image](https://user-images.githubusercontent.com/50234893/61200921-3fd19e80-a6e3-11e9-9c3e-46d6e00c41dd.png)
Correct symbols appear after clicking "anvendt" 

![image](https://user-images.githubusercontent.com/50234893/61201193-136a5200-a6e4-11e9-81a4-f51d986612d7.png)

**Comment by sashuk** [comment]
@JacobBirk Could you please specify if this happens after zooming in? Please consider the following case:
- load page with `zoom < 15` (so, the layer symbols are not shown)
- select all layer in the Intro modal
- zoom into the map with `zoom >= 15`
- the previously selected layers still do not show up

The observed case was fixed in https://github.com/sashuk/watsonc/commit/a6b1b5d5289d2ef4f76c9c977bfadd824022315c

**Comment by JacobBirk** [comment]
Selection all layers & continue
![image](https://user-images.githubusercontent.com/50234893/61432422-bd3e1e80-a930-11e9-9b9c-56bb21a4ebef.png)
The Calypso stations are shown, but not with correct symbols
After zoom
![image](https://user-images.githubusercontent.com/50234893/61432539-19a13e00-a931-11e9-8434-56c21e3c11f9.png)
Jupiter symbols are gray, which is fine
Zooming in should activate the correct symbols
![image](https://user-images.githubusercontent.com/50234893/61433085-a6003080-a932-11e9-9347-71dfc4a2788b.png)

Clicking "Anvend" returns:
![image](https://user-images.githubusercontent.com/50234893/61433123-bdd7b480-a932-11e9-8000-aa964166ca33.png)
which is fine

**Comment by sashuk** [comment]
@JacobBirk Thank you very much for the information! The actual data is loaded only with `zoom level >= 15`, as it could affect the performance a lot. Calypso points are displayed on lower zoom levels as the number of Calypso points is less than the Jupiter ones, so it will not affect the performance as well.

Fixed in https://github.com/sashuk/watsonc/commit/83272da00a07b7cc763384334cfa46f3c1e4b47e

Demo:
![control](https://user-images.githubusercontent.com/1390758/61508260-a7f1ee80-aa1b-11e9-963b-20c911e40843.gif)
