### ISSUE TITLE
Dashboard open & close

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#56]
I know that et was my suggestion, but I dont think appearance (closed, halv size and full size) of the dashboard works properly. Any suggestions?
I think you should re-introduce the arrows and - if possible - make the entire blue framed area clickable
![image](https://user-images.githubusercontent.com/50234893/61376345-4d348780-a8a1-11e9-94ef-20bf04c179b6.png)

**Comment by sashuk** [comment]
@JacobBirk Should arrows be in the middle of the framed area as they used to be?

**Comment by JacobBirk** [comment]
@sashuk Depends on #58.
If you can control the display order it would be fine in the middle. Otherwise the left (or both places)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Arrows are back - now the Dashboard can be minified/expanded via arrows **and** by clicking the header. The arrows were put at the left side in order to keep the header compact (placing arrows in the middle will make the statistics text go down which will take another line). Implemented in https://github.com/sashuk/watsonc/commit/1e68ae49c48f5f945556b3c841b3272c9c340af3.

![controls](https://user-images.githubusercontent.com/1390758/61431984-91875c80-a961-11e9-81ce-726cc0cecef0.PNG)

Demo:
![expanding](https://user-images.githubusercontent.com/1390758/61431977-8c2a1200-a961-11e9-9553-37353d61c32c.gif)

**Comment by JacobBirk** [comment]
perfect:-)
