### ISSUE TITLE
Sensordata not visible before zooming in to very small area

### ISSUE THREAD

**Issue by olemunch** [sashuk/watsonc#72]
@sashuk 
@mapcentia 
testing https://watsonc.vidi.gc2.io/app/jupiter/chemicals,sensor/#geodk.bright/7/9.4482/56.069/

Sensordata are not visible before zooming into a very little area.
 
In the url "sensordata_without_correction" occour, but this table does not exist anymore. Only sensordata_with_correction" contain the locations with sensordata to be shown. Is that related to this problem?

**Comment by sashuk** [comment]
@mapcentia Could you please specify if it is possible to create the alias for the `sensordata_with_correction` with the name `sensordata_without_correction` as it was before (actually it can be any name, it just should be different from the `sensordata_with_correction`)?

The reason is that it is not possible to display two representations of the same layer in Vidi now (which would be the vector `v:sensor.sensordata_with_correction` and the tile `sensor.sensordata_with_correction`), as there can be only one representation of the layer at the same time on the map. So, there are two options:

1. Modify the Vidi code (layer switching logic, layer tree building etc.) for all the Vidi instances;
2. Create an alias in the Watsonc database, so Vidi will not require any changes.

**Comment by WatsonC-hub** [comment]
@sashuk 
Hi Alexandr
We discussed this with Martin and decided that sensordata should be loaded in the browser for all zoom levels. So if I understand your question correctly the answer is, that only one reporesentation is needed. Could you check how long time i takes to load all sensordata and let ud now if this approach is not recommended?

Alternatively perhaps I can create a view in the database with the name "sensordata_without_correction"
/Ole

**Comment by sashuk** [comment]
@WatsonC-hub Sure, I will check how it loads all the stations as a vector layer (if it will take too much, then creating view will be an option, for now, the `sensordata_without_correction` layer will be removed completely from codebase).

**Comment by sashuk** [comment]
@WatsonC-hub Seems like it takes around 5 seconds to load all Calypso stations (the edge case), so I think it is okay to use only the vector representation.

![timing](https://user-images.githubusercontent.com/1390758/63158882-cebc3880-c04c-11e9-9b76-5d7a96751348.PNG)

**Comment by JacobBirk** [comment]
Perfect :-)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk The `sensordata_without_correction` layer was removed from the codebase and is no longer shown, implemented in https://github.com/sashuk/watsonc/commit/ef5573c4280725de3b9eb2b3bfeb9c34a5d5aad7.

Demo:
![layer](https://user-images.githubusercontent.com/1390758/63159632-89006f80-c04e-11e9-978b-6f47745b59f3.gif)
